### ISSUE TITLE
Sugestões de Layout

### ISSUE THREAD

**Issue by celioware** [bernunca/bernunca.github.io#1]
Talvez seja necessário alterar o Layout do website principal bernuncamozillacampus.club.

Envie sua sugestão {^_^}

**Comment by LuizdosReis** [comment]
acho que podemos colocar uma sessão com os nossos encontros e fotos

**Comment by benmezger** [comment]
Sim. Acho que mudar para Jekyll fica mais facil de gerar isso. O Juceio resolveu fazer isso tudo na mao.

**Comment by benmezger** [comment]
@LuizdosReis tá trabalhando na parte de fotos. Ver: #5 

Vou fechando esse issue por enquanto. Podemos discutir isso no Slack e publicar as mudancas por aqui. Abram qualquer coisa.
